### ISSUE TITLE
Do you have same library as this in iOS?

### ISSUE THREAD

**Issue by kazekim** [catchthecows/AndroidImageMap#12]
Thanks for good library. I need to use this library for my Android project but I need it in iOS too.I need to work with the same XML file. It can be more easier to work with.

Do you have same library as this in iOS?

Thanks

**Comment by catchthecows** [comment]
I don't have an iOS version. Though it might be a fun practice project in
Swift.

**Comment by kazekim** [comment]
Thanks. It may be good if we can use algorithm in iOS too but there are some logic that not work in iOS.I will try it first.

**Comment by dhgillani** [comment]
UISCrollview events + BezierPath in iOS helps you a lot.
